// Generated by scripts/generate-api.mjs — do not edit.
export interface paths {
  '/signup': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Public self-registration
     * @description Creates a new user account, always inactive and with an unvalidated email. An activation email is sent (when enabled) with a link to POST /users/activate.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['SignUpRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Email already exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/activate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Activate a self-registered account */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ActivateAccountRequest']
        }
      }
      responses: {
        /** @description Activated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unknown activation token */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Activation token expired */
        410: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search users */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UsersResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Create user (admin only) */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UserCreateRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Forbidden — requires ROLE_ADMIN */
        403: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/users/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get user */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description User ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['UsersResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    /** Delete user */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description User ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Deleted */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    /** Update user */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description User ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UserUpdateRequest']
        }
      }
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/users/{id}/change-password': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update user password */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description User ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ChangeUserPasswordRequest']
        }
      }
      responses: {
        /** @description Password updated correctly */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** User authentication */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['LoginRequest']
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/token-renew': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Renew JWT token */
    put: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            token?: string
          }
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['RenewTokenResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    post?: never
    /** Logout */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            token?: string
          }
        }
      }
      responses: {
        /** @description Success */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/configurations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search configurations */
    get: {
      parameters: {
        query?: {
          /** @description JSON array of {field, operator, value}, e.g. [{"field":"key","operator":"like","value":"mail."}] */
          filters?: components['schemas']['FiltersParameter']
          page?: components['schemas']['PageParameter']
          size?: components['schemas']['ItemsPerPageParameter']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ConfigurationSearchResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Create configuration */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ConfigurationCreateRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Key already exists */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Value does not match the declared type */
        422: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/configurations/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get configuration */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ConfigurationDetailResponse']
          }
        }
        /** @description Configuration not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    /** Delete configuration */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Deleted */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Configuration not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    /**
     * Update configuration value
     * @description Partial update — only the fields sent are changed. The key itself is immutable.
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['ConfigurationUpdateRequest']
        }
      }
      responses: {
        /** @description Updated */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Configuration not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Value does not match the declared type */
        422: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/configurations/{key}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get configuration change history
     * @description Returns an empty page for an unknown or already-deleted key rather than 404 — the ledger is meant to stay readable after the live configuration is gone.
     */
    get: {
      parameters: {
        query?: {
          page?: components['schemas']['PageParameter']
          size?: components['schemas']['ItemsPerPageParameter']
        }
        header?: never
        path: {
          key: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ConfigurationHistoryResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notifications': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search notifications */
    get: {
      parameters: {
        query?: {
          /** @description JSON array of {field, operator, value}, e.g. [{"field":"status","operator":"equals","value":"failed"}] */
          filters?: components['schemas']['FiltersParameter']
          page?: components['schemas']['PageParameter']
          size?: components['schemas']['ItemsPerPageParameter']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['NotificationSearchResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notifications/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get notification by id */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['NotificationDetailResponse']
          }
        }
        /** @description Notification not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notifications/{id}/retry': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Retry a failed notification
     * @description Moves a notification back to "pending" and re-dispatches delivery, re-rendering against the template's current content. Only valid from "failed" — retrying a "pending" or "sent" notification returns 409.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Notification not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Notification is not in a retryable state */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notification-templates': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Search notification templates */
    get: {
      parameters: {
        query?: {
          filters?: components['schemas']['FiltersParameter']
          page?: components['schemas']['PageParameter']
          size?: components['schemas']['ItemsPerPageParameter']
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['NotificationTemplateSearchResponse']
          }
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    /** Create notification template */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['NotificationTemplateCreateRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description A template already exists for this key/channel/locale */
        409: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid channel or key format */
        422: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notification-templates/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get notification template by id */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['NotificationTemplateDetailResponse']
          }
        }
        /** @description Notification template not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    put?: never
    post?: never
    /** Delete notification template */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description No content */
        204: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Notification template not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    options?: never
    head?: never
    /**
     * Update notification template
     * @description Partial update — only the fields sent are changed.
     */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['NotificationTemplateUpdateRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Notification template not found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Internal server error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    trace?: never
  }
  '/folders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create folder */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateFolderRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CreatedResponse']
          }
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Parent folder not found */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/folders/contents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List the contents of a folder (root when folder_id is omitted) */
    get: {
      parameters: {
        query?: {
          /** @description Folder to list. Omit for the root level. */
          folder_id?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['FolderContentsResponse']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/folders/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Move folder (with its contents) to the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    /** Rename folder */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['RenameFolderRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    trace?: never
  }
  '/folders/{id}/move': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Move folder to another parent (null = root) */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['MoveFolderRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Target folder not found or move would create a cycle (folder.cycle_detected) */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    trace?: never
  }
  '/folders/{folderId}/attachments': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload a file to a folder */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          folderId: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'multipart/form-data': components['schemas']['UploadAttachmentRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CreatedResponse']
          }
        }
        /** @description Missing "file" part */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create note */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['CreateNoteRequest']
        }
      }
      responses: {
        /** @description Created */
        201: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['CreatedResponse']
          }
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Folder not found */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/notes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get note */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['NoteDetailResponse']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    put?: never
    post?: never
    /** Move note to the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    /** Update note title and/or content */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['UpdateNoteRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    trace?: never
  }
  '/notes/{id}/move': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Move note to a folder (null = root) */
    patch: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': components['schemas']['MoveNoteRequest']
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Invalid data */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Target folder not found */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    trace?: never
  }
  '/attachments/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get attachment metadata */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Attachment ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['AttachmentDetailResponse']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    put?: never
    post?: never
    /** Move attachment to the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Attachment ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List everything in the trash */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['TrashResponse']
          }
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    put?: never
    post?: never
    /** Permanently delete everything in the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/folders/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restore a folder from the trash */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash (notes.not_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/folders/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Permanently delete a folder from the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Folder ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash (notes.not_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/notes/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restore a note from the trash */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash, or its parent folder is still in the trash (notes.not_in_trash / notes.parent_folder_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/notes/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Permanently delete a note from the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Note ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash (notes.not_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/attachments/{id}/restore': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Restore a attachment from the trash */
    post: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Attachment ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash, or its parent folder is still in the trash (notes.not_in_trash / notes.parent_folder_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/trash/attachments/{id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Permanently delete a attachment from the trash */
    delete: {
      parameters: {
        query?: never
        header?: never
        path: {
          /** @description Attachment ID */
          id: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Missing or invalid token */
        401: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not found (or owned by another user) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
        /** @description Not in the trash (notes.not_in_trash) */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['ApiError']
          }
        }
      }
    }
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    UserCreateRequest: {
      /** Format: uuid */
      id?: string
      email: string
      password: string
      username?: string
    }
    SignUpRequest: {
      /** Format: uuid */
      id?: string
      email: string
      password: string
      username?: string
    }
    ActivateAccountRequest: {
      token: string
    }
    UserUpdateRequest: {
      username?: string
      email?: string
      password?: string
      /** @default 0 */
      role: number
      /** @default true */
      active: boolean
      /** @default true */
      emailValidated: boolean
    }
    UserDetailResponse: {
      /** Format: uuid */
      id?: string
      username?: string
      email?: string
      role?: {
        id?: number
        name?: string
      }
      /** @default true */
      active: boolean
      /** @default true */
      emailValidated: boolean
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      lastLoginAt?: string
    }
    UserItemResponse: {
      /** Format: uuid */
      id?: string
      username?: string
      email?: string
      /** Format: date-time */
      createdAt?: string
      /** Format: date-time */
      lastLoginAt?: string
    }
    UsersResponse: {
      items?: components['schemas']['UserItemResponse'][]
      size?: number
      total?: number
      page?: number
      last?: number
    }
    ChangeUserPasswordRequest: {
      currentPassword: string
      newPassword: string
    }
    LoginRequest: {
      /** Format: email */
      email?: string
      /** Format: password */
      password?: string
    }
    RenewTokenResponse: {
      data?: {
        token?: string
      }
    }
    ConfigurationCreateRequest: {
      /** Format: uuid */
      id?: string
      /** @description Dot-namespaced, e.g. mail.sender_name. Immutable once created. */
      key: string
      value: string
      /** @enum {string} */
      type: 'string' | 'integer' | 'boolean' | 'json'
      description?: string | null
      /**
       * @description Encrypted at rest and never returned in plaintext once set.
       * @default false
       */
      is_sensitive: boolean
    }
    /** @description All fields optional — only the ones sent are changed. */
    ConfigurationUpdateRequest: {
      value?: string
      /** @enum {string} */
      type?: 'string' | 'integer' | 'boolean' | 'json'
      description?: string | null
      is_sensitive?: boolean
    }
    ConfigurationDetailResponse: {
      /** Format: uuid */
      id?: string
      key?: string
      /** @enum {string} */
      type?: 'string' | 'integer' | 'boolean' | 'json'
      description?: string | null
      is_sensitive?: boolean
      /** @description Always null when is_sensitive is true — this endpoint never reveals a sensitive value. */
      value?: string | null
      /** Format: date-time */
      created_at?: string
      /** Format: date-time */
      updated_at?: string
    }
    ConfigurationSearchResponse: {
      meta?: components['schemas']['ConfigurationPageMeta']
      data?: components['schemas']['ConfigurationDetailResponse'][]
    }
    ConfigurationHistoryEntry: {
      /** @enum {string} */
      action?: 'created' | 'updated' | 'deleted'
      previous_value?: string | null
      new_value?: string | null
      /** Format: uuid */
      changed_by?: string
      /** Format: date-time */
      changed_at?: string
    }
    ConfigurationHistoryResponse: {
      meta?: components['schemas']['ConfigurationPageMeta']
      data?: components['schemas']['ConfigurationHistoryEntry'][]
    }
    ConfigurationPageMeta: {
      page?: number
      size?: number
      total?: number
      last_page?: number
    }
    NotificationDetailResponse: {
      /** Format: uuid */
      id?: string
      /** @enum {string} */
      channel?: 'email'
      template_key?: string
      locale?: string
      recipient?: string
      /** Format: uuid */
      recipient_id?: string | null
      payload?: Record<string, never>
      subject?: string | null
      /** @enum {string} */
      status?: 'pending' | 'sent' | 'failed'
      attempts?: number
      last_error?: string | null
      provider_message_id?: string | null
      /** Format: date-time */
      sent_at?: string | null
      /** Format: date-time */
      created_at?: string
      /** Format: date-time */
      updated_at?: string
    }
    NotificationSearchResponse: {
      meta?: components['schemas']['NotificationPageMeta']
      data?: components['schemas']['NotificationDetailResponse'][]
    }
    NotificationPageMeta: {
      page?: number
      size?: number
      total?: number
      last_page?: number
    }
    NotificationTemplateCreateRequest: {
      /** Format: uuid */
      id?: string
      /** @description Dot-namespaced, e.g. user.welcome. Together with channel and locale, must be unique. */
      key: string
      /** @enum {string} */
      channel: 'email'
      /** @description e.g. en, es, en_US. Falls back to "en" at delivery time when no exact-locale template exists. */
      locale: string
      /** @description Sandboxed Twig source (if/for only, a short filter allowlist, no method/property access). */
      subject: string
      /** @description Sandboxed Twig source, same restrictions as subject. */
      body: string
      /** @default true */
      is_active: boolean
    }
    /** @description All fields optional — only the ones sent are changed. key/channel/locale are immutable once created. */
    NotificationTemplateUpdateRequest: {
      subject?: string
      body?: string
      is_active?: boolean
    }
    NotificationTemplateDetailResponse: {
      /** Format: uuid */
      id?: string
      key?: string
      /** @enum {string} */
      channel?: 'email'
      locale?: string
      subject?: string
      body?: string
      is_active?: boolean
      /** Format: date-time */
      created_at?: string
      /** Format: date-time */
      updated_at?: string
    }
    NotificationTemplateSearchResponse: {
      meta?: components['schemas']['NotificationPageMeta']
      data?: components['schemas']['NotificationTemplateDetailResponse'][]
    }
    CreatedResponse: {
      /** Format: uuid */
      id: string
    }
    CreateFolderRequest: {
      name: string
      /** Format: uuid */
      parent_folder_id?: string | null
    }
    RenameFolderRequest: {
      name: string
    }
    MoveFolderRequest: {
      /** Format: uuid */
      parent_folder_id?: string | null
    }
    MoveNoteRequest: {
      /** Format: uuid */
      folder_id?: string | null
    }
    CreateNoteRequest: {
      title: string
      /** @description Markdown */
      content?: string
      /** Format: uuid */
      folder_id?: string | null
    }
    UpdateNoteRequest: {
      title?: string
      /** @description Markdown */
      content?: string
    }
    UploadAttachmentRequest: {
      /** Format: binary */
      file: string
    }
    FolderSummary: {
      /** Format: uuid */
      id?: string
      name?: string
      /** Format: date-time */
      created_at?: string
    }
    NoteSummary: {
      /** Format: uuid */
      id?: string
      title?: string
      /** Format: date-time */
      created_at?: string
      /** Format: date-time */
      updated_at?: string
    }
    AttachmentSummary: {
      /** Format: uuid */
      id?: string
      file_name?: string
      mime_type?: string
      size_bytes?: number
      /** Format: date-time */
      created_at?: string
    }
    FolderContentsResponse: {
      /** @description The listed folder; null at the root level. */
      folder?: {
        /** Format: uuid */
        id?: string
        name?: string
        /** Format: uuid */
        parent_folder_id?: string | null
      } | null
      subfolders?: components['schemas']['FolderSummary'][]
      notes?: components['schemas']['NoteSummary'][]
      attachments?: components['schemas']['AttachmentSummary'][]
    }
    NoteDetailResponse: {
      /** Format: uuid */
      id?: string
      title?: string
      /** @description Markdown */
      content?: string
      /** Format: uuid */
      folder_id?: string | null
      /** Format: date-time */
      created_at?: string
      /** Format: date-time */
      updated_at?: string
    }
    AttachmentDetailResponse: {
      /** Format: uuid */
      id?: string
      /** Format: uuid */
      folder_id?: string
      file_name?: string
      mime_type?: string
      size_bytes?: number
      /** Format: date-time */
      created_at?: string
    }
    TrashResponse: {
      folders?: {
        /** Format: uuid */
        id?: string
        name?: string
        /** Format: uuid */
        parent_folder_id?: string | null
        /** Format: date-time */
        deleted_at?: string
      }[]
      notes?: {
        /** Format: uuid */
        id?: string
        title?: string
        /** Format: uuid */
        folder_id?: string | null
        /** Format: date-time */
        deleted_at?: string
      }[]
      attachments?: {
        /** Format: uuid */
        id?: string
        file_name?: string
        /** Format: uuid */
        folder_id?: string
        /** Format: date-time */
        deleted_at?: string
      }[]
    }
    ResponseOk: {
      /** @description Operation result (shape depends on the endpoint) */
      _result?: unknown
      _info?: components['schemas']['Info']
      /** @example [] */
      _error?: Record<string, never>[]
    }
    ResponseNotFound: {
      /** @example [] */
      _result?: Record<string, never>[]
      _info?: components['schemas']['Info']
      _error?: components['schemas']['ErrorNotFound']
    }
    ResponseUnprocessableContent: {
      /** @example [] */
      _result?: Record<string, never>[]
      _info?: components['schemas']['Info']
      _error?: components['schemas']['ErrorUnprocessableContent']
    }
    Info: {
      host?: string
      uri?: string
      method?: string
      params?: Record<string, never>[]
      time?: number
      status?: number
    }
    Clock: {
      date?: string
      timezone_type?: number
      timezone?: string
    }
    ErrorNotFound: {
      code?: string
      details?: {
        code?: string
        message?: string
      }
      /** @example 404 */
      status_code?: number
      message?: string
      reference?: string
      action?: string
    }
    ErrorUnprocessableContent: {
      code?: string
      details?: {
        code?: string
        message?: string
      }
      /** @example 422 */
      status_code?: number
      message?: string
      reference?: string
      action?: string
    }
    /** @description Body of every error response. `code` is a stable identifier (e.g. `security.bad_credentials`, `note.not_found`) meant to be mapped to a translation key by clients. */
    ApiError: {
      /** @example note.not_found */
      code: string
      message: string
      params?: Record<string, never>[]
      /** @example 404 */
      status: number
    }
    /** @example [{"field":"name","operator":"like","value":"Digi"}] */
    FiltersParameter: string
    /** @example 1 */
    PageParameter: number
    /** @example 12 */
    ItemsPerPageParameter: number
    /** @example  */
    OrderByParameter: string
    /** @example  */
    OrderDirection: string
    Error: {
      /** Format: int32 */
      code: number
      message: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
