// Generates src/data/api/schema.d.ts from openapi.json (or OPENAPI_URL).
//
// The backend currently serializes empty schemas as `[]` (PHP empty array) instead of `{}`,
// which makes the OpenAPI document invalid. We normalize those here without touching
// openapi.json, so it stays a faithful copy of what the backend publishes.
import { readFile, writeFile } from 'node:fs/promises'
import openapiTS, { astToString } from 'openapi-typescript'

const source = process.env.OPENAPI_URL ?? './openapi.json'
const output = 'src/data/api/schema.d.ts'

const raw = source.startsWith('http')
  ? await (await fetch(source)).json()
  : JSON.parse(await readFile(source, 'utf8'))

const SCHEMA_KEYS = new Set(['_result', 'items', 'additionalProperties'])
let fixed = 0
const normalize = (node, key) => {
  if (Array.isArray(node)) {
    if (node.length === 0 && SCHEMA_KEYS.has(key)) {
      fixed++
      return {}
    }
    return node.map((n) => normalize(n))
  }
  if (node && typeof node === 'object') {
    return Object.fromEntries(Object.entries(node).map(([k, v]) => [k, normalize(v, k)]))
  }
  return node
}

// A property with a `default` is optional for the caller: the server fills it in.
const ast = await openapiTS(normalize(raw), { defaultNonNullable: false })
await writeFile(
  output,
  `// Generated by scripts/generate-api.mjs — do not edit.\n${astToString(ast)}`,
)
console.log(`Wrote ${output}${fixed ? ` (normalized ${fixed} empty schemas)` : ''}`)
